In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [3]:
a=np.array([1,2,3,4,5,6])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
type(a)

numpy.ndarray

In [7]:
import array as ar

In [8]:
ar.array('i',[1,2,3,4,5,6])

array('i', [1, 2, 3, 4, 5, 6])

In [11]:
np.array([1.5,67,6,46,"aniket"])

array(['1.5', '67', '6', '46', 'aniket'], dtype='<U32')

In [12]:
np.array([1.5,67,6,46],ndmin=5)

array([[[[[ 1.5, 67. ,  6. , 46. ]]]]])

In [13]:
np.array([1.5,67,6,46],ndmin=3)

array([[[ 1.5, 67. ,  6. , 46. ]]])

In [14]:
np.array([1.5,67,6,46],ndmin=1)

array([ 1.5, 67. ,  6. , 46. ])

In [15]:
np.array([1.5,67,6,46],ndmin=0)

array([ 1.5, 67. ,  6. , 46. ])

In [17]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.array([[1,2,3],[4,5,6]],ndmin=3)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [22]:
np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])