In [1]:
import numpy as np

In [2]:
np.array([3,4,5,6,7])

array([3, 4, 5, 6, 7])

In [3]:
np.array([5,6,7, 5+7j, "aniket"  , 56.67])

array(['5', '6', '7', '(5+7j)', 'aniket', '56.67'], dtype='<U64')

In [4]:
a=np.array([5,6,7])

In [5]:
type(a)

numpy.ndarray

In [6]:
np.array([4 , 5,6,7 ] , dtype = complex)

array([4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j])

In [7]:
np.array([5,6,7,8,9] , dtype= str)

array(['5', '6', '7', '8', '9'], dtype='<U1')

In [8]:
type(np.asarray([4,5,6,7,8]))

numpy.ndarray

In [9]:
np.asarray([4,5,6,7] , dtype=np.float16)

array([4., 5., 6., 7.], dtype=float16)

In [10]:
mat = np.matrix([5,6])

In [11]:
mat

matrix([[5, 6]])

In [12]:
type(mat)

numpy.matrix

In [13]:
np.asanyarray(mat)

matrix([[5, 6]])

In [14]:
l = [3,4,5,6,7]
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [15]:
np.fromfunction(lambda i ,j : i ==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [16]:
np.fromfunction(lambda i ,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [17]:
np.fromfunction(lambda i , j : i ** i , (3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [4., 4., 4.]])

In [18]:
np.fromfunction(lambda i , j : i ** i , (3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [4, 4, 4]], dtype=int32)

In [19]:
np.fromstring("23 56" , sep= "" ) 

<ipython-input-19-494337cd8073>:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring("23 56" , sep= "" )


ValueError: string size must be a multiple of element size

In [ ]:
np.fromstring("23 56" , sep= "5" ) 

In [20]:
np.fromstring("4,6" ,sep = ',')

array([4., 6.])

In [21]:
a

array([5, 6, 7])

In [22]:
a1 = np.array([5,6,7,8,9])

In [23]:
a2 = np.array([[4,5,6,7,8,9]])

In [24]:
a1

array([5, 6, 7, 8, 9])

In [25]:
a2

array([[4, 5, 6, 7, 8, 9]])

In [26]:
a2.size

6

In [27]:
a3 = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

In [28]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
a3.ndim

2

In [30]:
a1.ndim

1

In [31]:
a1.size

5

In [32]:
a3.size


9

In [33]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
a1.shape

(5,)

In [35]:
a1

array([5, 6, 7, 8, 9])

In [36]:
a2

array([[4, 5, 6, 7, 8, 9]])

In [37]:
a2.shape

(1, 6)

In [38]:
 a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a3.shape

(3, 3)

In [40]:
np.array([(2,3,4,5,6) ,(3,4,6,7,8)])

array([[2, 3, 4, 5, 6],
       [3, 4, 6, 7, 8]])

In [41]:
range(10)

range(0, 10)

In [42]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
range(3,5)

range(3, 5)

In [45]:
np.arange(3,5.6,.2)

array([3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4])

In [46]:
np.array([(2,3,4,5,6), (3,4,5,6,7)])


array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [47]:
np.fromstring("46562526",sep="2")

array([46562526.])

In [48]:
np.fromstring("23 56", sep = "5")

array([23.,  6.])

In [49]:
np.linspace(2,3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [50]:
np.linspace(0,9,num = 10)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
np.linspace(3,5 , num = 5)

array([3. , 3.5, 4. , 4.5, 5. ])

In [52]:
np.zeros(4)

array([0., 0., 0., 0.])

In [53]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
a4 = np.zeros((2,2,3))

In [55]:
a4

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [56]:
a4.shape


(2, 2, 3)

In [57]:
a4.ndim

3

In [58]:
a4.size

12

In [59]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
np.ones((3,4)) + 3

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [61]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [62]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [65]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
np.arange(16)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [67]:
np.arange(16).reshape((1,16))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [68]:
np.arange(16).reshape((16,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [69]:
np.arange(16).reshape((2,4,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [70]:
np.arange(16).reshape((1,1,2,4,2))

array([[[[[ 0,  1],
          [ 2,  3],
          [ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11],
          [12, 13],
          [14, 15]]]]])

In [71]:
np.arange(16).reshape((2,-155643522543))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [72]:
np.arange(16).reshape((2,-3553,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [73]:
np.random.rand(2,3)

array([[0.35691065, 0.11817043, 0.65986031],
       [0.69046707, 0.22131592, 0.24854392]])

In [74]:
np.random.randn(4,5)

array([[-0.32100405, -0.72124843,  0.47807535, -0.08733127, -0.93639007],
       [ 0.73171113, -0.62924202,  0.58934114,  0.49025736, -0.91740181],
       [-0.34482714, -1.54579762,  0.82371476, -0.07888542,  0.01982664],
       [-1.03163522, -1.42865511, -0.02631172,  0.4130837 ,  1.42954218]])

In [75]:
np.random.seed(344646456)
np.random.randint(1,5,(4,3))

array([[3, 4, 4],
       [1, 4, 3],
       [1, 4, 3],
       [1, 1, 4]])

In [76]:
a5 = np.random.randint(2,6 , (3,4))

In [77]:
a5

array([[5, 3, 5, 4],
       [3, 2, 4, 2],
       [4, 3, 2, 2]])

In [78]:
np.sort(a5)

array([[3, 4, 5, 5],
       [2, 2, 3, 4],
       [2, 2, 3, 4]])

In [79]:
np.sort(a5,axis=1)

array([[3, 4, 5, 5],
       [2, 2, 3, 4],
       [2, 2, 3, 4]])

In [80]:
a5

array([[5, 3, 5, 4],
       [3, 2, 4, 2],
       [4, 3, 2, 2]])

In [81]:
a6 = np.random.randint(2,10 , (3,3))

In [82]:
a6

array([[7, 2, 2],
       [8, 6, 8],
       [9, 4, 8]])

In [83]:
np.sort(a6,axis=1,kind = 'mergesort')

array([[2, 2, 7],
       [6, 8, 8],
       [4, 8, 9]])

In [84]:
np.sort(a6,axis=0)

array([[7, 2, 2],
       [8, 4, 8],
       [9, 6, 8]])

In [85]:
np.sort(a6)

array([[2, 2, 7],
       [6, 8, 8],
       [4, 8, 9]])

In [86]:
a6

array([[7, 2, 2],
       [8, 6, 8],
       [9, 4, 8]])

In [87]:
a6.max()

9

In [88]:
a6[2]

array([9, 4, 8])

In [89]:
a6[2:1:1]

array([], shape=(0, 3), dtype=int32)

In [90]:
a7 = np.random.randint(3,7 , (6,6))

In [91]:
a7

array([[5, 5, 6, 3, 6, 4],
       [3, 5, 5, 3, 6, 3],
       [4, 4, 4, 5, 5, 4],
       [4, 3, 3, 6, 3, 6],
       [6, 3, 5, 3, 3, 3],
       [6, 6, 4, 3, 6, 3]])

In [92]:
a7[3]

array([4, 3, 3, 6, 3, 6])

In [93]:
a7[2:5,2:4]

array([[4, 5],
       [3, 6],
       [5, 3]])

In [94]:
a5 = np.random.randint(3,6 , (3,4 ))

In [95]:
a6 = np.random.randint(3,8, (3,4))

In [96]:
a5

array([[4, 3, 3, 3],
       [5, 5, 4, 5],
       [4, 5, 5, 4]])

In [97]:
a6

array([[6, 6, 5, 3],
       [6, 5, 4, 5],
       [3, 7, 5, 6]])

In [98]:
a5/0

<ipython-input-98-bdcb42fa6494>:1: RuntimeWarning: divide by zero encountered in true_divide
  a5/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [99]:
7/0

ZeroDivisionError: division by zero

In [100]:
a5

array([[4, 3, 3, 3],
       [5, 5, 4, 5],
       [4, 5, 5, 4]])

In [101]:
a6

array([[6, 6, 5, 3],
       [6, 5, 4, 5],
       [3, 7, 5, 6]])

In [102]:
a5*a6

array([[24, 18, 15,  9],
       [30, 25, 16, 25],
       [12, 35, 25, 24]])

In [103]:
a5/a6

array([[0.66666667, 0.5       , 0.6       , 1.        ],
       [0.83333333, 1.        , 1.        , 1.        ],
       [1.33333333, 0.71428571, 1.        , 0.66666667]])

In [104]:
a7 = np.random.randint(3,6 , (3,3))

In [105]:
a7

array([[3, 3, 3],
       [5, 5, 3],
       [3, 4, 3]])

In [106]:
a5/a7

ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 

In [107]:
a5

array([[4, 3, 3, 3],
       [5, 5, 4, 5],
       [4, 5, 5, 4]])

In [108]:
a6.T

array([[6, 6, 3],
       [6, 5, 7],
       [5, 4, 5],
       [3, 5, 6]])

In [109]:
a7


array([[3, 3, 3],
       [5, 5, 3],
       [3, 4, 3]])

In [110]:
a6.T@a7

array([[57, 60, 45],
       [64, 71, 54],
       [50, 55, 42],
       [52, 58, 42]])

In [111]:
a7

array([[3, 3, 3],
       [5, 5, 3],
       [3, 4, 3]])

In [112]:
a7 ** 3

array([[ 27,  27,  27],
       [125, 125,  27],
       [ 27,  64,  27]], dtype=int32)

In [113]:
np.empty((3,6))


array([[4.45057637e-308, 9.34604358e-307, 9.34605037e-307,
        1.11260483e-306, 1.78019354e-306, 4.45066125e-308],
       [9.34605037e-307, 1.60220393e-306, 1.24611674e-306,
        4.45057637e-308, 9.34597567e-307, 2.22523004e-306],
       [2.13620264e-306, 4.45063578e-308, 1.37961302e-306,
        8.45596650e-307, 5.73116149e-322, 2.13621350e-306]])